### ISSUE TITLE
Charset and  invalid characters

### ISSUE THREAD

**Issue by AdrianoTheSouza** [asfernandes/node-firebird-drivers#48]
Hello, I have a little problem, in my queries with the library I have received invalid characters like a : (?).

I believe it is because the database is with default charset "NONE", is there a way to set the same in the connection through the library? how to solve ?

Im using node firebird driver native

**Comment by asfernandes** [comment]
The best way to solve is to not use NONE in the database.

The driver does not treat it (because it should not exist in good databases).

The driver treat BINARY/OCTETS/VARBINARY as binary data and CHAR/VARCHAR as strings.

JavaScript does not have strings of binary data and that is probably your problem.

**Comment by AdrianoTheSouza** [comment]
Unfortunately for my use this is a problem because it is a legacy database that communicates with many other software, so it is not possible to change the current character set as it would affect other software that works with it.

Thanks for the answer, 
I'll be finishing the issue.
